### ISSUE TITLE
`ipfs-404.html` is not documented

### ISSUE THREAD

**Issue by jyooru** [ipfs/ipfs-docs#1155]
There is no documentation (as verified by a text search through this repository) on the `ipfs-404.html` file, which is returned if a file is not found. Only found out about this file by looking inside the folders of the official IPFS websites.

**Comment by johnnymatthews** [comment]
Thanks for raising this!

## Tasks

- [ ] Write a basic description for what the `ipfs-404.html` page does.
    - [ ] Can likely grab the **Custom 404 Pages** paragraph from this blog: https://blog.ipfs.io/2020-06-26-go-ipfs-0-6-0/
- [ ] Create an example `ipfs-404.html` page.
- [ ] Show the reader where to store this file.
- [ ] Show an example of what the file looks like on a webserver.
- [ ] Link to web services like Fleek: https://docs.fleek.co/hosting/troubleshooting/#adding-404-errors

**Comment by lidel** [comment]
Would it be possible to wait with documenting this until  `_redirects` file support  https://github.com/ipfs/go-ipfs/pull/8890 lands?
Or at least mention it as a better solution in the works that will supersede `ipfs-404.html`.

**Comment by TMoMoreau** [comment]
Closing this now, it has been addressed here: https://docs.ipfs.tech/how-to/websites-on-ipfs/redirects-and-custom-404s/
