### ISSUE TITLE
Add content about IPFS in resource constrained environments

### ISSUE THREAD

**Issue by 2color** [ipfs/ipfs-docs#1412]
## Background

Many ongoing projects explore how to use IPFS in resource-constrained environments such as mobile devices, web browsers, and IoT devices. 

Examples include [Aggregore](https://agregore.mauve.moe/), [Durin](https://github.com/ipfs-shipyard/Durin), and [Iroh](https://iroh.computer/), [Capyloon](https://capyloon.org/), and [ipfs-embed](https://github.com/ipfs-rust/ipfs-embed)

These rely on similar patterns, such as HTTP IPFS Gateways and "delegated providing" using pinning services (and the upcoming writeable gateway spec).

## Page goal

- Educate about the resources commonly needed by an IPFS node, e.g. access to TCP/UDP connections, no. of peers, being long-running (to continue publishing to the DHT), be publicly reachable
- Educate about the trade-offs, how some responsibilities can be delegated, and the landscape of options (delegated routing over HTTP with link to spec), delegated representation and providing pinning services, verified retrieval with gateways.
- link out to relevant tooling, libraries, and projects working on this.

## Tasks

- [x] Create PR for new page in Concepts section to capture info above with sections and links to the implementations page.
- [x] Create task list in PR
- [x] Link PR to this issue
- [x] Add PR to ipfs docs work board
- [x] Remove this issue from ipfs docs work board

**Comment by ElPaisano** [comment]
@2color this proposal makes sense.

Questions for you:
1. Do you think we could include all of this info in a single page? From your description, it seems like yes, with more or less one section for each of the bullet points you mentioned
2. If we condense this into a single page, where should that page go? From your description, this seems to me to be something that would fit into our Concepts category.

**Comment by 2color** [comment]
Yeah I would create a new page for this with sections and links to the implementations page.

The concepts section sounds like a good place for this

**Comment by ElPaisano** [comment]
@2color I started on https://github.com/ipfs/ipfs-docs/pull/1450 (still very much a draft) for this issue. I'll tag you in that PR once it's ready for  👀

**Comment by ElPaisano** [comment]
Reached out to team in [Slack](https://filecoinproject.slack.com/archives/C03FFEVK30F/p1680565282621649) requesting SME assistance to finish this. No response yet, depriortizing, as the team has not indicated that this PR is important to finish. Will repriortize if I hear back

**Comment by 2color** [comment]
Addressed by https://docs.ipfs.tech/how-to/ipfs-in-web-apps/. 

Closing
