### ISSUE TITLE
Epic: Update IPFS Concepts material

### ISSUE THREAD

**Issue by ElPaisano** [ipfs/ipfs-docs#1432]
**EDITED**

This is an epic issue to update and improve all material under https://docs.ipfs.tech/concepts/. List of individual issues below:

- [ ] https://github.com/ipfs/ipfs-docs/issues/1431
- [x] https://github.com/ipfs/ipfs-docs/issues/1433
- [ ] ... add more GH issues
