### ISSUE TITLE
Epic: Improvements to Projects section

### ISSUE THREAD

**Issue by ElPaisano** [ipfs/ipfs-docs#1435]
This is an epic issue to discuss and track improvement work for content currently living under https://docs.ipfs.tech/project/

Suggested tasks are as follows. Open to discussion. Some of these tasks can probably be grouped into a single PR:

- [ ] https://docs.ipfs.tech/project/ headers should reflect sidebar and summarize what's found in this section of the docs (including community stuff)
- [ ] Remove all top level hyperlinks in sidebar and nestings
- [ ] Content of "Join the community" sidebar menu should match headers on https://docs.ipfs.tech/community/
- [ ] Remove "Write the docs" submenu and better surface https://docs.ipfs.tech/community/contribute/ways-to-contribute/#documentation
- [x] #1437
- [ ] Review and update https://docs.ipfs.tech/project/implementation-status/
- [x] Should we still be linking to https://github.com/ipfs/roadmap?
- [ ] #1453
- [x] #1438
- [ ] ... other task????...

**Comment by ElPaisano** [comment]
@TMoMoreau can you take a look at this high level task list and let me know what you think? Can provide more details if some points aren't clear

**Comment by TMoMoreau** [comment]
What's the plan for removing the hyperlinks? I agree it's a little weird and can be jarring when clicking on when, not expecting a link to an outside website.

**Comment by ElPaisano** [comment]
@TMoMoreau RE 
> What's the plan for removing the hyperlinks?

I should probably describe it as "Removing and rearranging hyperlinks" - it's going to involve a mix of things and will relate to some of the other tasks on this list - gonna think a little more about this before creating an issue

**Comment by ElPaisano** [comment]
@TMoMoreau these ones are both pretty clear in scope I think

- [ ] #1437
- [ ] #1438
 
Do agree with the task / scope? If so, these would both be good first issues in this epic to pick up and create a PR for
