### ISSUE TITLE
Add Swiftype to IPFS Docs

### ISSUE THREAD

**Issue by johnnymatthews** [ipfs/ipfs-docs#1497]
Recently, Algolia search stopped working within IPFS Docs. This PR https://github.com/ipfs/ipfs-docs/pull/1489 switched the site back to using the default VuePress search. While the VuePress search does a _decent enough_ job, it'd be great to add IPFS Docs into the Protocol Labs Swiftype account so that we can better tailor the results that users get.

## Tasks

- [x] Add IPFS Docs to Swiftype account.
- [x] Index the site.
- [x] Add Swiftype JS content into this repo.
- [x] Test test test:
    - [x] I suggest we spin up a beta/test build for a week and see if we notice any bugs or weird things going on there.
- [ ] Merge.

**Comment by johnnymatthews** [comment]
Had issues applying a custom class into the navbar with VuePress. VuePress uses an external plugin to show a search, but there isn't an documentation on how to customize this plugin with the class that Swiftype needs to insert it's logic into a site.
