### ISSUE TITLE
Language 

### ISSUE THREAD

**Issue by Haosmozga** [ipfs/ipfs-docs#1827]
```[tasklist]
### Tasks
- [ ] https://github.com/ipfs/ipfs-docs/pull/1856
- [ ] https://github.com/ipfs/ipfs-docs/issues/1861
- [ ] https://github.com/ipfs/ipfs-docs/issues/1860
- [ ] https://github.com/ipfs/ipfs-docs/issues/1849
```
