### ISSUE TITLE
Launch Task List

### ISSUE THREAD

**Issue by hugomrdias** [ipfs/ipfs-docs#240]
- [x] make sure this is all done https://github.com/ipfs/ipfs-docs/issues/238
- [x] merge master into release branch
- [x] merge infra PR https://github.com/protocol/bifrost-infra/pull/764
- [x] merge release branch into master to launch
- [x] change naming in google analytics
  - UA-96910779-15 is docs.ipfs.io
  - UA-96910779-6 is olds docs

**Comment by cwaring** [comment]
I've deprecated the old Analytics (UA-96910779-6) and renamed the beta profile (UA-96910779-15) to the primary account now, so calling this migration complete now. Feel free to re-open if there are any outstanding tasks.
