### ISSUE TITLE
Check this repo for incorrect spelling automatically.

### ISSUE THREAD

**Issue by johnnymatthews** [ipfs/ipfs-docs#284]
To keep writing across the docs consistent, we're going to implement an automated spell-checker that checks markdown documents for errors. The spellchecker must let us add our own items into the dictionary. Unfortunately, Filecoin isn't a well-defined word. Yet.

## Tasks

- [ ] Investigate [markdown-it-spellcheck](https://github.com/matatk/markdown-it-spellcheck) as a solution.
- [ ] Add a spellchecker into `package.json`.
- [ ] Define and add words we need to add to the dictionary (IPFS, Filecoin, FIL, etc).
