### ISSUE TITLE
Explain how data encryption works with IPFS.

### ISSUE THREAD

**Issue by johnnymatthews** [ipfs/ipfs-docs#298]
IPFS deals with encryption in interesting ways. We need a general overview of how IPFS manages encryption, including:

- Where data is and is not encrypted.
- The difference between transport encryption and content encryption.
- Why IPFS doesn't include encryption _at rest_.
- Examples of projects that are using IPFS with encrypted data.

This overview should be similar in size and layout to the [IPFS Gateway overview](https://docs-beta.ipfs.io/concepts/ipfs-gateway/). This bounty will likely lead to further investigation and research bounties regarding IPFS encryption.

**Comment by ianopolous** [comment]
If you want to reference a design for encrypted content on ipfs that has been audited by professional cryptographers (super important for anything in this space), then have a look at Peergos. It also includes access control (granting and revoking R, RW or making public), *trustless* servers and privacy focused sovereign identity. 
https://book.peergos.org
https://github.com/peergos/peergos

**Comment by johnnymatthews** [comment]
How's progress @EricLScace?

**Comment by yusefnapora** [comment]
Here's a link to the dag-jose explainer we talked about in the sync meeting: https://www.memoryandthought.me/golang,/ipfs/2020/09/04/dag-jose-project.html

Also the js implementation repo: https://github.com/ceramicnetwork/js-dag-jose#jwe-encryption-usage

**Comment by johnnymatthews** [comment]
## Tasks

### Page set up

- [ ] Create a new section header in `concepts/privacy` called **Encryption**.
- [ ] Rename `concepts/privacy` to `concepts/privacy-and-encryption`.
    - [ ] Edit the title of the page to _Privacy and encryption_.
- [ ] Add a redirect for `/concepts/privacy` to `/concepts/privacy-and-encryption`.
- [ ] Update sidebar link to reflect the name and title change.

### Encryption content

- [ ] Explain:
    - [ ] Where data is and is not encrypted.
        - [ ] Diagram showing where data is and is not encrypted as it enters and leaves the network. This can be created in excalidraw.com
    - [ ] The difference between transport encryption and content encryption.
    - [ ] Why IPFS doesn't include encryption at rest.
    - [ ] Recommendations/best practices for encrypting data for publication/sharing on IPFS.
    - [ ] Examples of projects that are using IPFS with encrypted data.
