### ISSUE TITLE
Include community-managed bootstrap nodes to the Configure a Node page.

### ISSUE THREAD

**Issue by momack2** [ipfs/ipfs-docs#334]
We want to add optional community bootstrap nodes that ipfs users can add to their node configs to provide more diversity/resilience in the bootstrapping flow. Since a number of groups already have these nodes, we'd like to add a small section to the bottom of this page to list the additional bootstrap nodes, and what organization they're being run by. I'll add a list here to be merged in as I collect the right IDs from various operators. =]

**Comment by johnnymatthews** [comment]
This sounds like a _nice to have_ `P2` task. Can up the priority if you think it's urgent @momack2. The list of nodes can fit into [`how-to/configure-node/#bootstrap`](https://github.com/ipfs/ipfs-docs/blob/master/docs/how-to/configure-node.md#bootstrap) quite nicely.

**Comment by alexmmueller** [comment]
If the needed input is available @momack2 I would be happy to start with this issue.

**Comment by johnnymatthews** [comment]
This is tricky. Updating a list of public and live bootstrap nodes could be costly in terms of time. What would be better is if we had an automated service that observes the DHT and returns a set of stable peers that have been online for ~1 day or more.

**Comment by momack2** [comment]
I don't think that was quite the intended approach, @johnnymatthews. This issue came from sourcing/identifying additional mechanisms to heal from hypothetical DOS attacks against the pre-configured IPFS bootstrap node list that ships in go-ipfs. With a community list here in the docs, nodes could re-configure to new bootstrap nodes if those default nodes are ever DOSed in an attack (unable to bootstrap new nodes into the network). The todo items to make this possible are:

- [ ] Request "bootstrap" node addresses from IPFS Operators (ex @andrewxhill, @obo20, @MichaelMure, @bmann, etc)
- [ ] Make a table with those addresses that others can PR to

**Comment by momack2** [comment]
Maybe we can just start with this list here? https://docs.ipfs.io/how-to/peering-with-content-providers/#content-provider-list

**Comment by johnnymatthews** [comment]
Oh I see! So this list of nodes will act as a backup in case the default bootstrap nodes go down for whatever reason. Makes sense.

We could pretty easily make a workflow for users to create a PR to add new nodes. But:

- Should we allow any PR that adds a new node into the list, or only accept PRs from recognised IPFS community members? 
- Do regular IPFS users have to trust that these bootstrap nodes won't do anything malicious?

## Tasks

- [ ] Get list of alternative bootstrap nodes.
- [ ] Add node addresses to [`how-to/configure-node/#bootstrap`](https://github.com/ipfs/ipfs-docs/blob/master/docs/how-to/configure-node.md#bootstrap)
- [ ] List steps to change the bootstrap nodes your IPFS node looks for.

**Comment by momack2** [comment]
I think it can be fairly permissive - but some good standing in the ecosystem required (a malicious node could ex be annoying by bootstrapping new nodes into an isolated network and refuse to resolve content / peer them with other nodes).

**Comment by Annamarie2019** [comment]
I'll take this one (and also [683](https://github.com/ipfs/ipfs-docs/issues/683) and [245](https://github.com/ipfs/ipfs-docs/issues/245), to really get into nodes).

**Comment by Annamarie2019** [comment]
...in progress.

**Comment by Annamarie2019** [comment]
@johnnymatthews How/from whom or where do I "get list of alternative bootstrap nodes"? 

- Am I just cutting and pasting the current list from [how-to/content-provider-list](ipns://docs.ipfs.io/how-to/peering-with-content-providers/#content-provider-list)?
- Or am I narrowing it down?
- What does "community" mean....all on this list of just Protocol Labs?
- If we add this list the configure a node page, we'll have it in 2 places (no single source of truth). How will we keep updated, especially since updates are invited ("add yourself to the list")?

**Comment by Annamarie2019** [comment]
@johnnymatthews How do I know when I have a complete or at least a largely representative list of  IPFS Operators to request "bootstrap" node addresses from? So far we have:

- obo20 at Pinata
- andrewxhill at Textile
- MichaelMure at Infura (Do we need a peer id? Can I find this in Desktop?)
- bmann at Fission-Suite (Do we need a peer id?)

Can you tell me who else (or how I can find out), such as: 

- us for Protocol Labs, NFT.Storage, Web3.Storage (who? different operators for each product?)
- who at Cloudflare?
- any other companies?

**Comment by Annamarie2019** [comment]
Hello @andrewxhill, @obo20, @MichaelMure, @bmann,
We would like to provide a list of alternative bootstrap nodes in our [Configure a node > Bootstrap](https://docs.ipfs.io/how-to/configure-node/#bootstrap) documentation in the unlikely event of a Denial of Service attack for the sake of risk reduction. Can you provide me with a list for your organization?

**Comment by bmann** [comment]
Hey @Annamarie2019 thanks for the ping. We could run some community accessible nodes but right now we've turned off routing of non Fission content.

**Comment by johnnymatthews** [comment]
I've reached out to the IPFS team to see if we can get an authoritative list of community-ran bootstrap nodes.
