### ISSUE TITLE
Remove the "Install" section from the "Command-line quick start" guide.

### ISSUE THREAD

**Issue by marten-seemann** [ipfs/ipfs-docs#362]
There are two Install guides on docs.ipfs.io: https://docs.ipfs.io/install/command-line-quick-start/ and https://docs.ipfs.io/how-to/command-line-quick-start/. They are slightly different, for example, the latter one instructs Mac users to download the x86 version, which is not supported by current OSX versions any more.

When installing IPFS that way, users will run into problems with OSX Gatekeeper, since the binary is not properly signed. Maybe we should recommend using Homebrew to install IPFS? Otherwise, we might want to add some text how to add an exception for the Gatekeeper.

**Comment by johnnymatthews** [comment]
There's two issues here:

## We have two _quick-starts_.

Let's delete the quick start under the *How-tos* section.

- [ ] Delete the **Quick Start** section from **How-tos**.
- [ ] File a PR with the infrastructure team to add a redirect `/how-to/command-line-quick-start/   ->   /install/command-line-quick-start/`
- [ ] Remove `/how-to/command-line-quick-start/` from the sidebar.

## IPFS has issues installing on macOS.

There are several ways around this. Using Homebrew as you suggest, or by grabbing the Go-IPFS binary with `wget`. Although I believe the binaries at [`dist.ipfs.io` are signed](https://dist.ipfs.io/#go-ipfs). Would you be able to test this @marten-seemann?

**Comment by marten-seemann** [comment]
> There are several ways around this. Using Homebrew as you suggest, or by grabbing the Go-IPFS binary with wget. Although I believe the binaries at dist.ipfs.io are signed. Would you be able to test this @marten-seemann?

Github and dist.ipfs.io seem to serve the same files. Checking again, it also looks like I only get the Gatekeeper warning for the 32-bit version, not the 64-bits.

**Comment by johnnymatthews** [comment]
Thanks for checking in on that @marten-seemann. There likely needs to be a discussion around whether or not we should keep the 32-bit version. There's already an internal discussion on _how_ to drop support (seems very simple), we just need to decide whether or not we _should_. I'll update this issue with more information once it comes out.

**Comment by johnnymatthews** [comment]
[I created an issue to discuss dropping 32-bit macOS support](https://github.com/ipfs/distributions/issues/311). The result of that discussion was to _keep_ supporting 32-bit macOS, and fix the signing process, [which spawned a new issue](https://github.com/ipfs/distributions/issues/273).

So, the second part of this issue, _IPFS has issues installing on macOS_, will be fixed by the [new ipfs/distributions` issue #273](https://github.com/ipfs/distributions/issues/273). The first part of this issue, _We have two quick-starts_, still needs to be addressed.

**Comment by alexmmueller** [comment]
I am wondering if this is a good issue for me to start contributing? I have a product background and surely have a learning curve in working with github, but would be happy to help here.

**Comment by johnnymatthews** [comment]
This issue has changed from when it was first created. The [Install](https://docs.ipfs.io/how-to/command-line-quick-start/#install-ipfs) section of the [Command-line quick start](https://docs.ipfs.io/how-to/command-line-quick-start) is a duplicate of the [/install/command-line/](https://docs.ipfs.io/install/command-line/) page, so it needs to be removed. However, the rest of the **Command-line quick start** guide is still useful.

## Tasks

- [ ] Remove the Install IPFS section from the [Command-line quick start](https://docs.ipfs.io/how-to/command-line-quick-start/) guide.
- [ ] Add a prerequisites section to the Command-line quick start guide.
 - [ ] Instruct users to install Go-IPFS through the command-line if they haven't already.

Feel free to have a go at addressing these issues @alexmmueller. Fork this repository and make a PR against `master` once you have completed your work. I'll assign this issue to you.

**Comment by alexmmueller** [comment]
Thank you @johnnymatthews, will do so.

**Comment by alexmmueller** [comment]
Is there anything left to do for me here, or can the issue be closed?

**Comment by johnnymatthews** [comment]
Nope, that's everything! Thanks for your contribution @alexmmueller!
