### ISSUE TITLE
Walk web developers through creating an hosting a site on IPFS.

### ISSUE THREAD

**Issue by johnnymatthews** [ipfs/ipfs-docs#374]
Walk web developers through creating an hosting a site on IPFS.

One of the groups of users IPFS wants to target are web developers. We should have a section where users can create a simple website, host it on IPFS, and attach a domain name to it. This hands on series will teach readers how files websites can be managed with IPFS, and how to integrate their work into the IPFS ecosystem.

## Tasks

- [x] Host a single-page website
	- [x] Install IPFS Desktop
	- [x] Add a site
	- [x] Pin the files
- [x] Multi-page website
	- [x] Create a project folder for readers to use.
	- [x] Add the files to IPFS using IPFS Desktop.
- [x] Link a domain
	- [x] DNS
	- [x] ENS
- [x] Introduction to Fleek
- [x] Static-site generators
	- [x] Hugo
	- [x] VuePress
	- [x] Jekyll

**Comment by johnnymatthews** [comment]
@leon-do.
