### ISSUE TITLE
Explain how to reset an IPFS installation to the default profile.

### ISSUE THREAD

**Issue by johnnymatthews** [ipfs/ipfs-docs#385]
## [This issue has a bounty of $400](https://github.com/ipfs/devgrants/projects/1)

The following question was asked during the 2020 HackFS hackathon event:

> Which profile does `ipfs init` use by default.

We don't have an explicitly named _default_ profile, just the implicit one in `ipfs init`. The defaults are all [listed in the docs here](https://github.com/ipfs/go-ipfs/blob/master/docs/config.md). This can cause issues if the user wants to _reset_ their profile back to how everything was when they first installed IPFS.

While there likely need to be further work within Go-IPFS to address this issue, we can fix things in the docs by listing the default profile within the docs.

## Tasks

- [x] Add a _Default profile_ section to the **Customize your install** section.
- [x] Show the default profile/settings.
- [x] Lists the steps users should follow if they want to _reset_ their profile back to the default
    - [ ] We _could_ have a way for users to directly write to their `.config` file by running a single `curl` command, or something like that. This likely needs more discussion though.

**Comment by jay-dee7** [comment]
@johnnymatthews would it be okay for me to work on this?

**Comment by johnnymatthews** [comment]
@jay-dee7 , you've been assigned! Are you happy with the tasks above? If you've got any questions, just post them in here.

**Comment by jay-dee7** [comment]
Thanks @johnnymatthews and I've seen, by default flatfs is being used  as profile but let me go over this in detail over the weekend and I'll post any question here after that.

**Comment by jay-dee7** [comment]
hey @johnnymatthews i did spend some time with this, i have a question though. 
do we have cross-profile compatibility? So far what i could understand about profiles is that they're sort of underlying datastores for the ipfs nodes like `badgerds` uses Dgraph's badger KV and `flatfs` probably uses LevelDB. So if we have some data (bunch of files) inside our existing profile on our IPFS node, when we switch to a different profile, we have to kind of reinitialize the node, that could probably mean data losses. Is there an existing way to make this work? or am i going in the wrong direction?

**Comment by hsanjuan** [comment]
For the case where one profile uses badger and the other not (or viceversa), I think https://dist.ipfs.io/#ipfs-ds-convert must be used to migrate the data (unless that happens by default, try it out!). I don't remember the specific usage of this tool, but it may be that the flow is like:

1. Run ipfs-ds-convert with the right flags
2. Wait for migration to finish (I think it updates the configuration accordingly)
3. Apply new profile (if needed, as the migration may already update that part of the config)

**Comment by jay-dee7** [comment]
Thanks a ton @hsanjuan this is exactly what i was looking for. I'll give the above method a shot and prepare a draft from it :)

**Comment by jay-dee7** [comment]
hey guys, just a little update: 
I tried converting datastore using the `ipfs-ds-convert` looks like the master is broken. The usual `go get` didn't work, i had to navigate to the cloned repository and run `make install` and it worked. Also i checked, data does not get migrated by default and we have to first apply a profile, then convert the underlying datastore and then we're sort-of ready with our profile rollback/rollover. I'll possibly try to make a draft tomorrow 🤞

**Comment by johnnymatthews** [comment]
Closed in #545.
