### ISSUE TITLE
Explain how to start an IPFS node using a pre-generated private key.

### ISSUE THREAD

**Issue by johnnymatthews** [ipfs/ipfs-docs#386]
## [This issue has a bounty of $500](https://docs.google.com/spreadsheets/d/1m7Uc0HONbuCDbw2qGzTg3rFzt7CWNm2rjKnnMIsseFg/edit#gid=0)

This question was asked during the 2020 HackFS hackathon event:

> How can I start an IPFS node with pre-generated private key?

JS-IPFS has the [`options.init.privateKey` field](https://github.com/ipfs/js-ipfs/blob/master/packages/ipfs/docs/MODULE.md#optionsinit) you can pass to `IPFS.create`.

## Tasks

- [x] Find out if this process is possible with Go-IPFS.
- [x] Create a new section under **How-tos** > **Customize your install** called **Use existing private key**.
- [x] List the steps needed to start an IPFS instance using a pre-generated private key
    - [x] For Go-IPFS (if possible).
    - [x] For JS-IPFS
- [ ] Explain the benefits of using a pre-generated private key.
- [ ] Explain the security concerns of using a pre-generated private key.

**Comment by AlexxNica** [comment]
I like this one! Is there a limit to how many issues with bounties I can take at the same time? 😅

**Comment by johnnymatthews** [comment]
@AlexxNica we haven't set a hard limit, but to keep everything fair and open it might be an idea to set a limit of two bounties at once. That way we can have multiple people working on different issues at once, and we're not bottlenecked too much.

I'll assign you to this issue. Are you happy with the tasks outlined above? If you've got any questions, just post them in here :)

**Comment by AlexxNica** [comment]
@johnnymatthews Perfect! I agree with that limit and think it's good to have such a limit so we can let more people collaborate.

I'm happy with the tasks! I'll let you know if any questions emerge!

Thank you, Johnny! 😃

**Comment by johnnymatthews** [comment]
Thanks for your initial PR @AlexxNica! I've merged it into the `pre-production` branch. But, I just noticed that the last two tasks above still need to be completed. There's no rush, but when you get the time can you please complete the two remaining tasks:

> - [ ] Explain the benefits of using a pre-generated private key.
> - [ ] Explain the security concerns of using a pre-generated private key.

You're best the make your branch based off the `pre-production` branch so that things get merged in a bit easier. Thanks!

**Comment by AlexxNica** [comment]
Hey, @johnnymatthews! I've taken some time off and am coming back now. Sorry for any delays!

On the tasks you mentioned, I don't see a direct benefit or specific security concern for using pre-generated private keys. I believe that both depend solely on the problem the developer is trying to solve. So what I did instead was to [present use cases instead of benefits](https://github.com/ipfs/ipfs-docs/pull/568/files#diff-f762df086a6ff7b489201d6b905db16d7ef030f0362cc24fca40e8386c9d68c9R79) (to show a perspective on what's possible), and a general section about security, that [you've reviewed and found to be unnecessary](https://github.com/ipfs/ipfs-docs/pull/568#discussion_r545320926).

What do you think? I can do a more thorough research on this if you feel they can be different from what I've already added to the document.

**Comment by johnnymatthews** [comment]
Ah! Thanks for the reminder! Not sure why I marked it as unnecessary if I created an issue for it. I must've ran out of tea that day.

I've just created #618 to re-add it. And your other point is fair, the use-cases work to explain the benefit of using private keys.
