### ISSUE TITLE
Improve the landing page for the Install section.

### ISSUE THREAD

**Issue by johnnymatthews** [ipfs/ipfs-docs#415]
The **Install** section is getting a revamp with more sub-sections being added. Because of these new sub-sections, we'll need to direct users to where they need to get to.

## Tasks

- [x] Define the different user groups (developers, folks who want to store stuff, researchers, infrastructure engineers, lost Filecoiners)
- [x] Define what each user-group is trying to achieve.
- [x] Create a header for each user-group with a paragraph explaining what they're likely trying to do, and link to the correct installation section:
    - For example: infra engineers want to build a network of IPFS nodes to host data, so push them towards to IPFS Cluster install section, and explain why that's the best option.
