### ISSUE TITLE
Explain why hashes are different between systems.

### ISSUE THREAD

**Issue by johnnymatthews** [ipfs/ipfs-docs#430]
# [This issue has a bounty of $200 USD](https://github.com/ipfs/devgrants/projects/1)

This issue cropped up from a discussion in IPFS IRC.

It somewhat frequently comes up that people ask or wonder why if they do `ipfs add ubuntu.iso` the resulting SHA256 _multihash_ has nothing to do with what they'd get running `sha256sum ubuntu.iso` (or with the hash posted on the Ubuntu website). Depending on the user, this question can come across using various levels of our jargon (e.g., I'm looking for the hash, not the multihash, or how do I turn a CID into a hash), but the idea is the same.

It may be useful to explain why this happens and what's going on. This issue is also likely a UX problem with IPFS itself, and might not be fixable from a purely docs perspective.

Here's an explanation put forward by @aschmahmann:

> CIDs are a format for used for identified content in a self describing way. They come with a base encoding, codec (i.e. what kind of data is the CID referring to), and a multihash.
> 
> Multihashes are a format for identifying hashes in a self describing way. Their point is to make it obvious that the thing you are looking at is a SHA-512 that's been truncated to 256 bits instead of a SHA-256 in it's entirety (it turns out people actually do these sorts of things with hash functions).
>
> IPLD utilizes the properties of merkle trees where if I have two pieces of data with hashes A and B, then I can refer to both of those pieces of data together uniquely by hashing the data structure that contains A and B and gives me C. As a result for any arbitrarily large tree of data identified by hashes there is a root node R whose hash identifies the entire tree including all of its children.
> 
> UnixFS is a particular IPLD format that was designed to take files, folders, etc. and structure them as merkle trees. For example, it's very helpful to p2p data transfer protocols like bitswap that instead of asking for a single 100 MB file they can ask for 100 one MB files. The root of this merkle tree that has many nodes that ultimately contain a 100MB file identifies the entire 100MB file as well as the graph structure/layout of the small blocks of data that make up the tree.
> 
> When you say that you have the CID of a file what you're really saying is that you have a reference to the root of a tree that includes all the data in your file.
> 
> This means that your question is ultimately: "Is there a way for me to determine the hash of the "file" part of the data given only the hash of the root of the tree that contains the file data?".
>
> In general the answer is no. For example, while it's obvious how to sha256 a file how do you sha256 a directory, as there are multiple ways the data could be structured. In the particular case of getting the sha256 of UnixFS files the answer is also no. However, it's certainly possible to create combinations of hash functions and data structures such that HashOfRoot = MyHashFunction(FileData) (as a dumb example MyHashFunction(FileData) could be just taking the result of ipfs add FileData). Is there a way to create a data structure for storing a file in a tree where the root hash happens to give you sha256 of the file data? Not that I know of, but perhaps possible.
>
> As an aside: CIDs are pretty generally useful. For example, if you have the SHA256 of some file (e.g. an Ubuntu ISO) you might decide to describe that using a CID (e.g. with a raw codec) so that it's easier to work with and becomes self describing. 

## Tasks

- [ ] Add a new section to [/concepts/hashing/](https://docs.ipfs.io/concepts/hashing/#hashes-are-important) called something like _Not all hashes are the same_ or something along those lines.
- [ ] Bring up the example above, stating that _the hashes Ubuntu shows for their `ISO`s are different from IPFS hashes because_...
- [ ] Show the math of how hashes are calculated using an incredibly simple hashing algorithm.
    - [ ] Change one variable in that algorithm, but feed it the same input string to show how different hashing functions produce different hashes, even when hashing the same file.

**Comment by alexmmueller** [comment]
@johnnymatthews I can give this one a try if you like.

**Comment by johnnymatthews** [comment]
It's all yours @alexmmueller! Drop your questions in here if you have any.
