### ISSUE TITLE
Explore adding a one-liner to the command-line install instructions.

### ISSUE THREAD

**Issue by johnnymatthews** [ipfs/ipfs-docs#489]
# [This issue has a bounty of $50](https://github.com/ipfs/devgrants/projects/1)

@mburns brought up that they prefer to copy-and-paste the install instructions into a terminal. It might be handy to see if we can create _one-liners_ that download, unzip, install, and test the Go-IPFS install.

So the Linux install could look something like this:

```bash
wget https://dist.ipfs.io/go-ipfs/v0.7.0/go-ipfs_v0.7.0_linux-amd64.tar.gz && tar -xvzf go-ipfs_v0.7.0_linux-amd64.tar.gz && cd go-ipfs && sudo bash install.sh && ipfs --version
```

Not sure if `wget` comes installed by default on Ubuntu, but I'm pretty sure `curl` does. We'd have to make sure that all _one-liners_ use the default software, and don't need any extra packages.

## Tasks

- [ ] Create a _one-liner_ for:
    - [ ] macOS @jay-dee7
    - [ ] Windows
    - [ ] Linux
        - [x] Ubuntu 20.04 @johnnymatthews @bertrandfalguiere 

## One-liners

It'd be handy if folks could test the following one-liners and then comment with any issues you run into:

### macOS

```bash
curl https://dist.ipfs.io/go-ipfs/v0.7.0/go-ipfs_v0.7.0_darwin-amd64.tar.gz -O && tar -xvzf go-ipfs_v0.7.0_darwin-amd64.tar.gz
```

### Windows

No command, yet.

### Linux

```bash
wget https://dist.ipfs.io/go-ipfs/v0.7.0/go-ipfs_v0.7.0_linux-amd64.tar.gz && tar -xvzf go-ipfs_v0.7.0_linux-amd64.tar.gz && cd go-ipfs && sudo bash install.sh && ipfs --version
```

**Comment by bertrandfalguiere** [comment]
Yes, wget is installed by default on Ubuntu. 
The above one-liner works on Ubuntu 20.04.

**Comment by jay-dee7** [comment]
@johnnymatthews AFAIK MacOS comes preinstalled with libcurl, this command works just fine on MacOS 
`curl https://dist.ipfs.io/go-ipfs/v0.7.0/go-ipfs_v0.7.0_darwin-amd64.tar.gz -O && tar -xvzf go-ipfs_v0.7.0_darwin-amd64.tar.gz`

**Comment by alexmmueller** [comment]
That's true @jay-dee7. I use MacOS Catalina: curl is preinstalled, wget is not. On windows PowerShell I can confirm that wget (with parameter -OutFile) works out of the box.

**Comment by johnnymatthews** [comment]
Commenting here before I forgot. Powershell users need to set their [script execution policy to `RemoteSigned`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7):

```powershell
Set-ExecutionPolicy -ExecutionPolicy RemoteSigned
```                                                                                                                                                            

The above line has to be ran as admin.

**Comment by johnnymatthews** [comment]
This issue isn't necessary anymore since we've got package manager installs towards the top of the CLI install page.
