### ISSUE TITLE
Re-check the "Link a domain" tutorial is still relevant.

### ISSUE THREAD

**Issue by eminence** [ipfs/ipfs-docs#539]
Hello!

In the Website on IPFS  /  Link a Domain section of the docs, there is a reference to the `www.gateway.ipfs.io` domain.  But this domain doesn't exist.   Can the docs be updated to include the correct domain name to use for a CNAME?

Here's a link to the published docs that make this reference:
https://docs.ipfs.io/how-to/websites-on-ipfs/link-a-domain/#domain-name-service-dns 
See step (2) under "Things you'll need":

 > Add a `CNAME` record and set the value to `www.gateway.ipfs.io.`

Or see line 26 of the source code:
https://github.com/ipfs/ipfs-docs/blob/108101154bb8a2aa89b385e43a0d9770934fb763/docs/how-to/websites-on-ipfs/link-a-domain.md

**Comment by johnnymatthews** [comment]
Hmm, something may have changed along the way. It's been a few months since that tutorial was created, so we'll have to run through it again to see if it needs updating. It could probably do with some screenshots to spice things up a little bit too.

## Tasks

- [ ] Run through the [Link a domain](https://docs.ipfs.io/how-to/websites-on-ipfs/link-a-domain/#domain-name-service-dns) tutorial.
- [ ] Check the DNS steps are still appropriate.
- [ ] Add some screenshots where necessary.
