### ISSUE TITLE
Import "run Go-IPFS in Docker" instructions.

### ISSUE THREAD

**Issue by johnnymatthews** [ipfs/ipfs-docs#586]
The [Go-IPFS repo readme](https://github.com/ipfs/go-ipfs#running-ipfs-inside-docker) has [instructions for running the a Go-IPFS node with Docker](https://github.com/ipfs/go-ipfs#running-ipfs-inside-docker). We should bring these instructions into this repo.

## Tasks

- [x] Create branch for this issue.
- [x] Create a new page for Docker.
- [x] Copy the content over from [github.com/ipfs/go-ipfs#running-ipfs-inside-docker](https://github.com/ipfs/go-ipfs#running-ipfs-inside-docker)
- [x] Update and fix grammar, spelling, and formatting.

In the future, we can expand this page into a hands-on Docker tutorial, but for now we can just point readers to here.
