### ISSUE TITLE
Explore including IPFS updater docs in this repo.

### ISSUE THREAD

**Issue by johnnymatthews** [ipfs/ipfs-docs#614]
[The IPFS updater](https://github.com/ipfs/ipfs-update#from-source) is a key project that, while not explicitly within the Protocol Labs org, is heavily relied on within the IPFS Docs. With this in mind, we should explore bringing any IPFS updater docs into this repo.

## Tasks

- [ ] Find out if there is enough relevant info/docs to bring into this repo.
    - [ ] If yes: list those docs, including any relevant blog posts/forum posts/external tutorials.
    - [ ] If no: close this issue with an explanation for why we're not bring IPFS updater docs into this repo.

**Comment by johnnymatthews** [comment]
This issue's gone stale. The docs team is focused on NFT and Filecoin docs at the moment, so the single-source-documentation project is on hold for a while. We'll revisit these issues in the future.
