### ISSUE TITLE
Include IPNS within the "Websites on IPFS" section.

### ISSUE THREAD

**Issue by adrapper** [ipfs/ipfs-docs#619]
This page is just fantastic. 

I miss-typed index.html which gave me some trouble, but I am not at the moment back in the habit of having to be VERY precise. 

One thing that is not mentioned. It is probably very obvious to anyone who is experienced in IPFS, but if I change the content of the folder, will the CID for that folder change. I think it would and therefore pointing a domain at it really is only practical after you have a website that is finished and will not change. 

If I am wrong and you can change the content.... wow!

Maybe a change could be made to make this point clear.

**Comment by johnnymatthews** [comment]
So, you've touched on a fairly important point here @adrapper; how to change content without having the change the CID a domain is looking at. The best way to get around this is to use [IPNS](https://docs.ipfs.io/concepts/ipns/#interplanetary-name-system-ipns). I won't go into too much detail here, but the main idea is that users can give other users a CID that itself do not change, but the content that the CID points to can change.

We could do with adding a step into either the domains section, or just create a completely new page, that walks users through using IPNS with their website.

## Tasks

- [ ] Create a new page within _How tos_ -> _Websites on IPFS_.
- [ ] Walk readers through adding their root CID to an IPNS CID.
- [ ] Add that IPNS CID to a domain name.

**Comment by adrapper** [comment]
I am not sure if we should reply to these updates or if that just give you more work…

But Thanks. 

It would be nice if in the how to "give other users a CID that itself do not change, but the content that the CID points to can change.” You could also talk about weather this is a final solution or just a workaround until a better implementation is reached. 

Thanks again. 

Andrew
