### ISSUE TITLE
Add Wordpress to the "Static-site generators" section of "Websites on IPFS".

### ISSUE THREAD

**Issue by Faheem955** [ipfs/ipfs-docs#627]
Please add about how to integrate WordPress with IPFS on this page in the documentation.
http://docs.ipfs.io.ipns.localhost:8080/how-to/websites-on-ipfs/static-site-generators/#jekyll

Thanks a lot.

**Comment by johnnymatthews** [comment]
Since Wordpress isn't techincally a static-site generator, I don't want to add a full guide into this section. However, we could absolutely link to [Fleek's How to Deploy a Wordpress Website onto IPFS guide](https://blog.fleek.co/posts/wordpress+fleek).

## Tasks

- [ ] Create a new subsection in `how-to/websites-on-ipfs/static-site-generators` called **Wordpress**.
- [ ] Explain that, while Wordpress isn't a static-site generator, it is possible to move a Wordpress site over to IPFS using Fleek.
- [ ] Link to the Fleek tutorial: https://blog.fleek.co/posts/wordpress+fleek
