### ISSUE TITLE
[nft tutorial] Finish example app

### ISSUE THREAD

**Issue by yusefnapora** [ipfs/ipfs-docs#692]
The example app [minty](https://github.com/yusefnapora/minty) is "mostly working", but there's some polishing left to do:

- [ ] [finalize CLI interface](https://github.com/yusefnapora/minty/issues/1)
- [ ] [implement web ui for viewing tokens](https://github.com/yusefnapora/minty/issues/2)
- [ ] [use js-ipfs remote pinning api](https://github.com/yusefnapora/minty/issues/3)
