### ISSUE TITLE
Review "Simple chat app" tutorial.

### ISSUE THREAD

**Issue by johnnymatthews** [ipfs/ipfs-docs#798]
PR #797 merged in a new _simple chat app_ tutorial. While the tutorial structure is sound, I haven't yet ran through the tutorial end-to-end to test that everything works fine.

## Tasks

- [ ] Read through _Create a simple chat app_ tutorial.
- [ ] Follow all the steps to eventually create the app.
- [ ] Note any inconsistencies here.

If there's anything glaringly wrong with the tutorial, let's use this issue to capture new to-dos.

**Comment by gmelodie** [comment]
I'll give this one a shot! Since I'm a newcomer to IPFS, I hope my insight will be somewhat useful :)

**Comment by johnnymatthews** [comment]
@Annamarie2019's [edit is in review](https://docs.google.com/document/d/1TYDr0_UJn_CAI_sWiKahTZclT1fd69hsDx6dQv2Nz3s/edit?usp=sharing).
