### ISSUE TITLE
Explore how to link and CID and a Handshake domain.

### ISSUE THREAD

**Issue by johnnymatthews** [ipfs/ipfs-docs#866]
The [Websites on IPFS](https://docs.ipfs.io/how-to/websites-on-ipfs/single-page-website/#install-ipfs-desktop) tutorial talks about linking up an [ENS domain to a CID](https://docs.ipfs.io/how-to/websites-on-ipfs/link-a-domain/#ethereum-naming-service-ens), but doesn't mention Handshake domains. A few hackathon participants have requested that it'd be nice to see a similar explanation for Handshake domains.

## Tasks

- [ ] Explore Handshake domains to see if it's possible to link a CID to them.
- [ ] Create a new section in `how-to/websites-on-ipfs/link-a-domain/` called `Handshake`.
- [ ] Add steps to link a CID to a Handshake domain.
